// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var TwoFer$TwoFer = require("../src/TwoFer.bs.js");

Jest.describe("Two Fer", (function (param) {
        Jest.test("no name given", (function (param) {
                return Jest.Expect.toEqual("One for you, one for me.", Jest.Expect.expect(TwoFer$TwoFer.twoFer(undefined)));
              }));
        Jest.test("a name given", (function (param) {
                return Jest.Expect.toEqual("One for Alice, one for me.", Jest.Expect.expect(TwoFer$TwoFer.twoFer("Alice")));
              }));
        return Jest.test("another name given", (function (param) {
                      return Jest.Expect.toEqual("One for Bob, one for me.", Jest.Expect.expect(TwoFer$TwoFer.twoFer("Bob")));
                    }));
      }));

/*  Not a pure module */
