// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function twoFer(name) {
  var determineName = function (name) {
    if (name !== undefined) {
      return name;
    } else {
      return "you";
    }
  };
  return "One for " + (determineName(name) + ", one for me.");
}

exports.twoFer = twoFer;
/* No side effect */
