# Credo used outside of mix as a standalone archive. Installation instructions:
# https://github.com/rrrene/credo#using-credo-as-stand-alone
tests exercise_filename test_filename:
  mix format --dot-formatter ~/exercism/elixir/.formatter.exs
  elixir {{test_filename}}
  mix credo --strict {{exercise_filename}}
